@baseUrl = http://localhost:5454
@auth = Basic aa:a

###

GET {{baseUrl}}/status

###

GET {{baseUrl}}/api/auth
Authorization: {{auth}}

###

POST {{baseUrl}}/api/users
Authorization: {{auth}}
Content-Type: application/json

{
    "username": "admin",
    "password": "123",
    "admin": true,
    "active": true
}

###

PUT {{baseUrl}}/api/users/4
Authorization: {{auth}}
Content-Type: application/json

{
    "username": "a",
    "password": "aa"
}

###

GET {{baseUrl}}/api/users
Authorization: {{auth}}
Content-Type: application/json

###

POST {{baseUrl}}/api/upload
Authorization: {{auth}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryosFv4xxeUbP0jjyQ

------WebKitFormBoundaryosFv4xxeUbP0jjyQ
Content-Disposition: form-data; name="fallbackDate"

2021-01-02 15:04:05
------WebKitFormBoundaryosFv4xxeUbP0jjyQ
Content-Disposition: form-data; name="url"

https://i.pinimg.com/236x/b0/1e/8d/b01e8d3165fe28957895ab08e2e10bd6--tasters-choice-nescafe.jpg
------WebKitFormBoundaryosFv4xxeUbP0jjyQ--

###

POST {{baseUrl}}/api/upload
Authorization: {{auth}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryosFv4xxeUbP0jjyQ


------WebKitFormBoundaryosFv4xxeUbP0jjyQ
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./test2.jpg
------WebKitFormBoundaryosFv4xxeUbP0jjyQ--

###

POST {{baseUrl}}/api/upload
Authorization: {{auth}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryosFv4xxeUbP0jjyQ


------WebKitFormBoundaryosFv4xxeUbP0jjyQ
Content-Disposition: form-data; name="file"; filename="test3.mp4"
Content-Type: video/mp4

< ./test3.mp4
------WebKitFormBoundaryosFv4xxeUbP0jjyQ--

###

GET {{baseUrl}}/test12/2021-06/fhvMHdH4M.jpg
Authorization: {{auth}}

###

GET {{baseUrl}}/1/2021-07-16/3/test3.mp4?size=300
Authorization: {{auth}}

###

GET {{baseUrl}}/api/media
Authorization: {{auth}}

###

GET {{baseUrl}}/api/media/2
Authorization: {{auth}}

###