name: Create Release
on:
  push:
    tags:
      - 'v*'
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        working-directory: ./backend
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: altlimit/dmedia:latest
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build backend
        working-directory: ./backend
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dmedia-linux-amd64
          env GOOS=windows GOARCH=amd64 go build -o dmedia-win-amd64.exe
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Build mobile
        working-directory: ./mobile
        run: |
          flutter pub get
          flutter build apk --release
      - name: Prepare builds
        run: |
          mkdir build
          mv backend/dmedia-linux-amd64 build/
          mv backend/dmedia-win-amd64.exe build/
          mv mobile/build/app/outputs/flutter-apk/app-release.apk build/
      - name: Create Release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);
            
            const fs = require('fs').promises;
            
            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });
            const releaseName = process.env.GITHUB_REF.split('/').pop();
            const release = await github.repos.createRelease({
                owner, repo,
                tag_name: releaseName,
                release_name: 'Release ' + releaseName,
                draft: false,
                body: await fs.readFile('RELEASE.md', 'utf8'),
                target_commitish: sha
            });
            console.log('created release', { release });        
            for (let file of await fs.readdir('./build')) {
                console.log('uploading', file);
                await github.repos.uploadReleaseAsset({
                    owner, repo,
                    release_id: release.data.id,
                    name: file,
                    data: await fs.readFile(`./build/${file}`)
                });            
            }