name: Release Backend
on:
  push:
    paths:
      - "backend/**"
    tags:
      - 'v*'
    
jobs:
  build:
    name: Create Backend Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: altlimit/dmedia:latest
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build backend
        working-directory: ./backend
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dmedia-linux-amd64
          env GOOS=windows GOARCH=amd64 go build -o dmedia-win-amd64.exe
      - name: Prepare builds
        run: |
          mkdir build
          mv backend/dmedia-linux-amd64 build/
          mv backend/dmedia-win-amd64.exe build/
          export "GIT_TAG_MSG=`echo $(git tag -l --format='%(contents:subject)' v0.0.2)`"
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install npm deps
        run: npm install execa
      - name: Create Backend Release
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |                        
            const fs = require('fs').promises;
            const execa = require('execa');            
            const { repo: { owner, repo }, sha } = context;
            const releaseName = process.env.GITHUB_REF.split('/').pop();
            const { stdout } = await execa('git', ['tag', '-l', "--format=%(contents:subject)", releaseName]);
            const release = await github.repos.createRelease({
                owner, repo,
                tag_name: releaseName,
                name: 'Server ' + releaseName,
                draft: false,
                body: stdout,
                target_commitish: sha
            });
            for (let file of await fs.readdir('./build')) {
                console.log('uploading', file);
                await github.repos.uploadReleaseAsset({
                    owner, repo,
                    release_id: release.data.id,
                    name: file,
                    data: await fs.readFile(`./build/${file}`)
                });            
            }